version: "4.0"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4173:4173"
      - "5173:5173"
    restart: always
    volumes:
      - /config:/config
      - /data:/data

volumes:
  config:
  data:
